<script setup lang="ts">
import SectionTitle from '@/components/SectionTitle.vue'
import ListRow from '@/components/ListRow.vue'
import AiFab from '@/components/AiFab.vue'
import { usePetStore } from '@/stores/pet'
const store = usePetStore()
const actions = [{ label: '成长', icon: 'camera', path: '/pages/growth/index' }, { label: '提醒', icon: 'notification', path: '/pages/reminder/index' }, { label: '报告', icon: 'list', path: '/pages/report/index' }]
function go(path: string) { uni.navigateTo({ url: path }) }
function back() { uni.navigateBack() }
</script>
<template><view class="screen"><view class="top"><view @tap="back"><uni-icons type="arrow-left" size="23" color="#1C1C1E" /></view><text>豆包</text><view><uni-icons type="more-filled" size="21" color="#1C1C1E" /></view></view><view class="body"><view class="profile"><image :src="store.pet.avatar" mode="aspectFill" /><text>{{ store.pet.name }}</text><text>{{ store.pet.breed }} · {{ store.pet.gender }} · {{ store.pet.age }}</text><view class="profile-stats"><view><text>{{ store.pet.weight }} <small>kg</small></text><text>当前体重</text></view><view><text>{{ store.pet.arrivedDays }}</text><text>相伴天数</text></view><view><text>良好</text><text>生活状态</text></view></view></view><view class="shortcut"><view v-for="action in actions" :key="action.label" @tap="go(action.path)"><view><uni-icons :type="action.icon" size="20" color="#007AFF" /></view><text>{{ action.label }}</text></view></view><SectionTitle title="最近动态" /><view class="group"><ListRow v-for="log in store.logs.slice(0, 4)" :key="log.id" :icon="log.icon" :tint="log.tint" :title="log.title" :note="`${log.date} · ${log.time}`" :value="log.value" :chevron="false" /></view><SectionTitle title="AI 发现" /><view class="insight" @tap="go('/pages/ai/index')"><view><uni-icons type="chat-filled" size="18" color="#007AFF" /></view><view><text>近 30 天体重保持稳定</text><text>饮食和体重趋势没有发现明显波动。</text></view><uni-icons type="arrow-right" size="16" color="#8E8E93" /></view><view class="spacer" /></view><AiFab @tap="go('/pages/ai/index')" /></view></template>
<style scoped lang="scss">
@use '@/styles/tokens.scss' as *;
.screen { min-height: 100vh; background: $canvas; }.top { display: flex; height: 118rpx; align-items: flex-end; justify-content: space-between; padding: 0 32rpx 20rpx; background: $canvas; }.top > view { display: flex; width: 64rpx; height: 64rpx; align-items: center; justify-content: center; border-radius: 50%; background: $surface; }.top > text { font-size: 32rpx; font-weight: 600; }.body { padding: 8rpx 32rpx; }.profile { display: flex; flex-direction: column; align-items: center; padding: 32rpx 24rpx 0; border-radius: 32rpx; background: $surface; }.profile image { width: 150rpx; height: 150rpx; border: 5rpx solid #fff; border-radius: 50%; box-shadow: 0 6rpx 18rpx rgba(0,0,0,.08); }.profile > text:nth-of-type(1) { margin-top: 17rpx; color: $ink; font-size: 42rpx; font-weight: 700; }.profile > text:nth-of-type(2) { margin-top: 7rpx; color: $tertiary; font-size: 22rpx; }.profile-stats { display: flex; width: 100%; margin-top: 28rpx; padding: 22rpx 0; border-top: 1rpx solid $separator; }.profile-stats view { display: flex; width: 33%; flex-direction: column; align-items: center; gap: 8rpx; border-right: 1rpx solid $separator; }.profile-stats view:last-child { border: 0; }.profile-stats text:first-child { color: $ink; font-size: 29rpx; font-weight: 600; }.profile-stats small { color: $secondary; font-size: 18rpx; font-weight: 400; }.profile-stats text:last-child { color: $tertiary; font-size: 19rpx; }.shortcut { display: flex; margin-top: 20rpx; padding: 18rpx 0; border-radius: 28rpx; background: $surface; }.shortcut > view { display: flex; width: 33%; flex-direction: column; align-items: center; gap: 9rpx; }.shortcut > view > view { display: flex; width: 56rpx; height: 56rpx; align-items: center; justify-content: center; border-radius: 17rpx; background: $blue-soft; }.shortcut text { color: $secondary; font-size: 21rpx; }.group { @include grouped-surface; }.insight { display: flex; align-items: center; padding: 22rpx; border-radius: 28rpx; background: $blue-soft; }.insight > view:first-child { display: flex; width: 58rpx; height: 58rpx; align-items: center; justify-content: center; border-radius: 18rpx; background: #fff; }.insight > view:nth-child(2) { display: flex; flex: 1; flex-direction: column; gap: 6rpx; margin-left: 16rpx; }.insight text:first-child { color: $ink; font-size: 26rpx; font-weight: 600; }.insight text:last-child { color: $secondary; font-size: 21rpx; }.spacer { height: 110rpx; }
</style>
