<script setup lang="ts">
import { computed, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import ListRow from '@/components/ListRow.vue'
import QuickRecordSheet from '@/components/QuickRecordSheet.vue'
import { usePetStore } from '@/stores/pet'
import type { RecordType } from '@/types/domain'
const store = usePetStore(); const type = ref<RecordType>('feeding'); const sheet = ref(false)
const configs: Record<RecordType, { title: string; cta: string; description: string }> = { feeding: { title: '喂食', cta: '添加喂食记录', description: '本月平均每日主粮 73 g' }, weight: { title: '体重', cta: '添加体重记录', description: '近 30 天体重保持稳定' }, water: { title: '饮水', cta: '添加饮水记录', description: '今日已记录 120 ml' }, toilet: { title: '排便', cta: '添加排便记录', description: '最近状态正常' }, event: { title: '日常事件', cta: '添加日常事件', description: '留住每一个小瞬间' } }
onLoad((options) => { if (options?.type && options.type in configs) type.value = options.type as RecordType })
const config = computed(() => configs[type.value]); const filtered = computed(() => store.logs.filter((item) => item.type === type.value))
function goAi() { uni.navigateTo({ url: `/pages/ai/index?context=${type.value}` }) }
</script>
<template><view class="screen"><view class="intro"><view><text>{{ config.title }}</text><text>{{ config.description }}</text></view><button v-if="type === 'weight'" @tap="goAi">AI 分析</button></view><view v-if="type === 'weight'" class="trend"><view class="trend-head"><text>近 7 天</text><text>5.2 kg</text></view><view class="columns"><view v-for="(height, index) in [58, 66, 74, 70, 80, 88, 92]" :key="height"><view :style="{ height: `${height}rpx` }" /><text>{{ index + 12 }}</text></view></view><text class="trend-note">体重趋势平稳，较上次记录增加 0.1 kg</text></view><text class="section-label">最近记录</text><view v-if="filtered.length" class="group"><ListRow v-for="log in filtered" :key="log.id" :icon="log.icon" :tint="log.tint" :title="log.title" :note="`${log.date} · ${log.time}${log.note ? ` · ${log.note}` : ''}`" :value="log.value" :chevron="false" /></view><view v-else class="empty"><uni-icons type="compose" size="38" color="#C7C7CC" /><text>还没有{{ config.title }}记录</text><text>从第一条开始，慢慢建立豆包的生活档案。</text></view><button class="add" @tap="sheet = true">{{ config.cta }}</button><QuickRecordSheet v-model="sheet" :type="type" /></view></template>
<style scoped lang="scss">
@use '@/styles/tokens.scss' as *;
.screen { min-height: 100vh; padding: 28rpx 32rpx 148rpx; background: $canvas; }.intro { display: flex; align-items: center; justify-content: space-between; padding: 25rpx; border-radius: 28rpx; background: $surface; }.intro view { display: flex; flex-direction: column; gap: 8rpx; }.intro text:first-child { font-size: 34rpx; font-weight: 700; }.intro text:last-child { color: $tertiary; font-size: 22rpx; }.intro button { margin: 0; padding: 0 17rpx; border-radius: 99rpx; background: $blue-soft; color: $blue; font-size: 22rpx; line-height: 56rpx; }.trend { margin-top: 20rpx; padding: 24rpx; border-radius: 28rpx; background: $surface; }.trend-head { display: flex; justify-content: space-between; }.trend-head text:first-child { font-size: 27rpx; font-weight: 600; }.trend-head text:last-child { color: $blue; font-size: 25rpx; font-weight: 600; }.columns { display: flex; height: 148rpx; align-items: flex-end; justify-content: space-between; margin-top: 18rpx; padding: 0 8rpx; border-bottom: 1rpx solid $separator; }.columns > view { display: flex; flex-direction: column; align-items: center; justify-content: flex-end; gap: 8rpx; color: $tertiary; font-size: 18rpx; }.columns > view > view { width: 16rpx; border-radius: 99rpx 99rpx 0 0; background: $blue; }.trend-note { display: block; margin-top: 16rpx; color: $tertiary; font-size: 21rpx; }.section-label { display: block; margin: 40rpx 0 14rpx 24rpx; color: $secondary; font-size: 24rpx; font-weight: 500; }.group { @include grouped-surface; }.empty { display: flex; flex-direction: column; align-items: center; gap: 15rpx; margin: 140rpx 32rpx 0; color: $secondary; font-size: 27rpx; }.empty text:last-child { color: $tertiary; text-align: center; font-size: 21rpx; line-height: 1.6; }.add { position: fixed; right: 32rpx; bottom: 40rpx; left: 32rpx; border-radius: 99rpx; background: $blue; box-shadow: 0 10rpx 22rpx rgba(0,122,255,.23); color: #fff; font-size: 29rpx; line-height: 92rpx; }
</style>
