<script setup lang="ts">
import { ref } from 'vue'
import ListRow from '@/components/ListRow.vue'
const notifications = ref(true); const privateOnly = ref(true)
function toast(label: string) { uni.showToast({ title: `${label}将在接入服务后可用`, icon: 'none' }) }
</script>
<template><view class="screen"><view class="account"><view class="mark">F</view><view><text>FaFa</text><text>记录宠物一生的 AI 生活助手</text></view></view><text class="section-label">通知</text><view class="group"><view class="switch-row"><view><text>提醒通知</text><text>在重要日子提醒你</text></view><switch :checked="notifications" color="#007AFF" @change="notifications = !notifications" /></view></view><text class="section-label">隐私与数据</text><view class="group"><view class="switch-row"><view><text>仅自己可见</text><text>照片和记录默认不公开</text></view><switch :checked="privateOnly" color="#007AFF" @change="privateOnly = !privateOnly" /></view><ListRow icon="download" tint="blue" title="导出我的数据" @tap="toast('导出数据')" /></view><text class="section-label">关于</text><view class="group"><ListRow icon="info" tint="gray" title="关于 FaFa" value="0.2.0" @tap="toast('关于 FaFa')" /><ListRow icon="help" tint="gray" title="用户协议与隐私政策" @tap="toast('用户协议')" /></view><view class="notice"><text>你的数据由你掌控</text><text>FaFa 不会将你的宠物照片和生活记录用于公开展示。</text></view><button class="logout" @tap="toast('退出登录')">退出登录</button></view></template>
<style scoped lang="scss">
@use '@/styles/tokens.scss' as *;
.screen { min-height: 100vh; padding: 32rpx; background: $canvas; }.account { display: flex; align-items: center; padding: 23rpx; border-radius: 28rpx; background: $surface; }.mark { display: flex; width: 72rpx; height: 72rpx; align-items: center; justify-content: center; border-radius: 22rpx; background: $blue; color: #fff; font-size: 35rpx; font-weight: 700; }.account > view:nth-child(2) { display: flex; flex-direction: column; gap: 6rpx; margin-left: 16rpx; }.account text:first-child { color: $ink; font-size: 28rpx; font-weight: 600; }.account text:last-child { color: $tertiary; font-size: 20rpx; }.section-label { display: block; margin: 40rpx 0 14rpx 24rpx; color: $secondary; font-size: 24rpx; font-weight: 500; }.group { @include grouped-surface; }.switch-row { display: flex; min-height: 106rpx; align-items: center; justify-content: space-between; padding: 18rpx 24rpx; border-bottom: 1rpx solid $separator; }.switch-row > view { display: flex; flex-direction: column; gap: 6rpx; }.switch-row text:first-child { color: $ink; font-size: 28rpx; }.switch-row text:last-child { color: $tertiary; font-size: 21rpx; }.notice { display: flex; flex-direction: column; gap: 8rpx; margin-top: 32rpx; padding: 22rpx; border-radius: 24rpx; background: $blue-soft; }.notice text:first-child { color: $blue; font-size: 25rpx; font-weight: 600; }.notice text:last-child { color: $secondary; font-size: 21rpx; line-height: 1.55; }.logout { margin-top: 34rpx; border: 1rpx solid #FFB6B1; border-radius: 99rpx; background: transparent; color: $red; font-size: 27rpx; line-height: 84rpx; }
</style>
