<script setup lang="ts">
import { ref } from 'vue'
import { usePetStore } from '@/stores/pet'
const store = usePetStore(); const detail = ref<'month' | 'week' | null>(null)
const reports = [{ type: 'month' as const, label: '月报', date: '2026 年 8 月', title: '八月，平静又充实', description: '体重稳定、记录充实，还有 12 张新照片。' }, { type: 'week' as const, label: '周报', date: '8 月 10 日 — 16 日', title: '一周生活小结', description: '饮食规律、提醒完成、生活一切正常。' }]
function generate() { uni.showToast({ title: '已开始生成本周报告', icon: 'none' }) }
</script>
<template><view class="screen"><template v-if="!detail"><view class="hero"><image :src="store.pet.avatar" mode="aspectFill" /><view><text>报告中心</text><text>把记录变成看得懂的陪伴。</text></view></view><view class="new" @tap="generate"><view><uni-icons type="plus" size="19" color="#007AFF" /></view><text>生成一份新报告</text><uni-icons type="arrow-right" size="15" color="#C7C7CC" /></view><text class="section-label">已生成的报告</text><view v-for="report in reports" :key="report.label" class="report" @tap="detail = report.type"><image :src="store.pet.avatar" mode="aspectFill" /><view><view><text>{{ report.label }}</text><text>{{ report.date }}</text></view><text>{{ report.title }}</text><text>{{ report.description }}</text></view><uni-icons type="arrow-right" size="16" color="#C7C7CC" /></view></template><template v-else><view class="detail-top"><view @tap="detail = null"><uni-icons type="arrow-left" size="22" color="#1C1C1E" /></view><text>{{ detail === 'month' ? '8 月月报' : '本周报告' }}</text><view><uni-icons type="more-filled" size="20" color="#1C1C1E" /></view></view><view class="detail"><text class="headline">{{ detail === 'month' ? '八月，平静又充实' : '这一周，豆包过得很好' }}</text><text class="desc">每一条记录，都让你更了解豆包的生活。</text><image :src="store.pet.avatar" mode="aspectFill" /><text class="section-label">本{{ detail === 'month' ? '月' : '周' }}概览</text><view class="numbers"><view><text>26</text><text>记录天数</text></view><view><text>92</text><text>喂食记录</text></view><view><text>12</text><text>新增照片</text></view></view><text class="section-label">AI 总结</text><view class="summary"><uni-icons type="chat-filled" size="18" color="#007AFF" /><text>豆包本月整体状态稳定。平均每日主粮摄入量较上月减少约 4%，体重没有明显变化；8 月 14 日已完成驱虫。</text></view></view></template></view></template>
<style scoped lang="scss">
@use '@/styles/tokens.scss' as *;
.screen { min-height: 100vh; padding: 30rpx 32rpx 80rpx; background: $canvas; }.hero { display: flex; align-items: center; padding: 24rpx; border-radius: 30rpx; background: $surface; }.hero image { width: 88rpx; height: 88rpx; border-radius: 50%; }.hero view { display: flex; flex-direction: column; gap: 8rpx; margin-left: 17rpx; }.hero text:first-child { color: $ink; font-size: 32rpx; font-weight: 700; }.hero text:last-child { color: $tertiary; font-size: 21rpx; }.new { display: flex; align-items: center; gap: 15rpx; margin-top: 20rpx; padding: 21rpx; border-radius: 25rpx; background: $blue-soft; }.new > view { display: flex; width: 54rpx; height: 54rpx; align-items: center; justify-content: center; border-radius: 17rpx; background: $surface; }.new > text { flex: 1; color: $blue; font-size: 27rpx; font-weight: 600; }.section-label { display: block; margin: 40rpx 0 14rpx 24rpx; color: $secondary; font-size: 24rpx; font-weight: 500; }.report { display: flex; align-items: center; margin-top: 15rpx; padding: 17rpx; border-radius: 28rpx; background: $surface; }.report image { width: 126rpx; height: 126rpx; border-radius: 19rpx; }.report > view { display: flex; flex: 1; flex-direction: column; gap: 7rpx; margin-left: 16rpx; }.report > view > view { display: flex; gap: 8rpx; }.report > view > view text:first-child { padding: 3rpx 8rpx; border-radius: 99rpx; background: $blue-soft; color: $blue; font-size: 17rpx; }.report > view > view text:last-child { color: $tertiary; font-size: 18rpx; }.report > view > text:nth-child(2) { color: $ink; font-size: 27rpx; font-weight: 600; }.report > view > text:last-child { overflow: hidden; color: $tertiary; font-size: 20rpx; text-overflow: ellipsis; white-space: nowrap; }.detail-top { display: flex; height: 74rpx; align-items: center; justify-content: space-between; }.detail-top > view { display: flex; width: 60rpx; height: 60rpx; align-items: center; justify-content: center; border-radius: 50%; background: $surface; }.detail-top > text { color: $ink; font-size: 29rpx; font-weight: 600; }.detail { padding-top: 34rpx; }.headline { display: block; color: $ink; font-size: 46rpx; font-weight: 700; line-height: 1.25; letter-spacing: -1rpx; }.desc { display: block; margin-top: 14rpx; color: $secondary; font-size: 23rpx; }.detail > image { width: 100%; height: 290rpx; margin-top: 28rpx; border-radius: 28rpx; }.numbers { display: flex; padding: 22rpx 0; border-radius: 27rpx; background: $surface; }.numbers view { display: flex; width: 33%; flex-direction: column; align-items: center; gap: 8rpx; border-right: 1rpx solid $separator; }.numbers view:last-child { border: 0; }.numbers text:first-child { color: $ink; font-size: 31rpx; font-weight: 700; }.numbers text:last-child { color: $tertiary; font-size: 19rpx; }.summary { display: flex; align-items: flex-start; gap: 14rpx; padding: 23rpx; border-radius: 26rpx; background: $blue-soft; }.summary text { flex: 1; color: $secondary; font-size: 24rpx; line-height: 1.65; }
</style>
