<script setup lang="ts">
import { computed, ref } from 'vue'
import { usePetStore } from '@/stores/pet'
const store = usePetStore(); const filter = ref<'active' | 'done'>('active'); const showing = computed(() => store.reminders.filter((item) => filter.value === 'active' ? !item.done : item.done))
function finish(id: string) { store.completeReminder(id); uni.showToast({ title: '已完成，已添加到成长档案', icon: 'success' }) }
function add() { uni.showToast({ title: '新建提醒将在接入服务后开放', icon: 'none' }) }
</script>
<template><view class="screen"><view class="segment"><view :class="{ active: filter === 'active' }" @tap="filter = 'active'">待完成 <text>{{ store.activeReminders.length }}</text></view><view :class="{ active: filter === 'done' }" @tap="filter = 'done'">已完成</view></view><view class="body"><view class="tip"><uni-icons type="notification-filled" size="16" color="#007AFF" /><text>完成提醒后，会自动写入成长时间轴。</text></view><view v-if="showing.length" class="group"><view v-for="item in showing" :key="item.id" class="reminder"><view class="icon" :class="item.tint"><uni-icons :type="item.icon" size="19" :color="item.tint === 'green' ? '#34C759' : item.tint === 'orange' ? '#FF9500' : '#007AFF'" /></view><view><text>{{ item.title }}</text><text>{{ item.date }} · {{ item.repeat }}</text></view><button v-if="!item.done" @tap="finish(item.id)">完成</button><uni-icons v-else type="checkbox-filled" size="22" color="#34C759" /></view></view><view v-else class="empty"><uni-icons type="checkbox" size="39" color="#C7C7CC" /><text>还没有已完成的提醒</text></view></view><button class="add" @tap="add">新建提醒</button></view></template>
<style scoped lang="scss">
@use '@/styles/tokens.scss' as *;
.screen { min-height: 100vh; background: $canvas; }.segment { display: flex; height: 90rpx; gap: 44rpx; padding: 0 32rpx; background: $surface; }.segment view { position: relative; display: flex; align-items: center; color: $tertiary; font-size: 28rpx; }.segment view.active { color: $ink; font-weight: 600; }.segment view.active::after { position: absolute; right: 5rpx; bottom: 0; left: 5rpx; height: 5rpx; border-radius: 99rpx; background: $blue; content: ''; }.segment text { margin-left: 6rpx; color: $blue; font-size: 19rpx; }.body { padding: 28rpx 32rpx 148rpx; }.tip { display: flex; align-items: center; gap: 11rpx; padding: 20rpx; border-radius: 21rpx; background: $blue-soft; color: $secondary; font-size: 22rpx; }.group { @include grouped-surface; margin-top: 20rpx; }.reminder { display: flex; min-height: 112rpx; align-items: center; padding: 18rpx 24rpx; border-bottom: 1rpx solid $separator; }.reminder:last-child { border: 0; }.icon { display: flex; width: 62rpx; height: 62rpx; align-items: center; justify-content: center; border-radius: 18rpx; }.icon.blue { background: $blue-soft; }.icon.green { background: #EAF8EF; }.icon.orange { background: #FFF3E2; }.reminder > view:nth-child(2) { display: flex; flex: 1; flex-direction: column; gap: 7rpx; margin-left: 17rpx; }.reminder > view:nth-child(2) text:first-child { color: $ink; font-size: 28rpx; font-weight: 600; }.reminder > view:nth-child(2) text:last-child { color: $tertiary; font-size: 21rpx; }.reminder button { margin: 0; padding: 0 20rpx; border-radius: 99rpx; background: $blue-soft; color: $blue; font-size: 22rpx; line-height: 56rpx; }.empty { display: flex; flex-direction: column; align-items: center; gap: 14rpx; margin-top: 150rpx; color: $secondary; font-size: 26rpx; }.add { position: fixed; right: 32rpx; bottom: 40rpx; left: 32rpx; border-radius: 99rpx; background: $blue; box-shadow: 0 10rpx 22rpx rgba(0,122,255,.23); color: #fff; font-size: 29rpx; line-height: 92rpx; }
</style>
