<script setup lang="ts">
import AppHeader from '@/components/AppHeader.vue'
import AppTabbar from '@/components/AppTabbar.vue'
import ListRow from '@/components/ListRow.vue'
import { usePetStore } from '@/stores/pet'
const store = usePetStore()
function go(path: string) { uni.navigateTo({ url: path }) }
function toast(title: string) { uni.showToast({ title: `${title}将在正式版开放`, icon: 'none' }) }
</script>
<template><view class="screen"><AppHeader title="我的" subtitle="林小满" action="gear" @action="go('/pages/settings/index')" /><view class="body"><view class="user"><view class="avatar">林</view><view><text>林小满</text><text>和 {{ store.pet.name }} 已一起生活 {{ store.pet.arrivedDays }} 天</text></view><uni-icons type="arrow-right" size="16" color="#C7C7CC" /></view><text class="section-label">我的宠物</text><view class="pet" @tap="go('/pages/pet/detail')"><image :src="store.pet.avatar" mode="aspectFill" /><view><text>{{ store.pet.name }}</text><text>{{ store.pet.breed }} · {{ store.pet.age }}</text></view><uni-icons type="arrow-right" size="16" color="#C7C7CC" /></view><text class="section-label">服务</text><view class="group"><ListRow icon="list" tint="blue" title="报告中心" note="查看每一次成长总结" @tap="go('/pages/report/index')" /><ListRow icon="chat" tint="blue" title="AI 助手" note="问问关于豆包的任何事" @tap="go('/pages/ai/index')" /><ListRow icon="notification" tint="orange" title="提醒管理" note="照顾好每一件小事" @tap="go('/pages/reminder/index')" /></view><text class="section-label">更多</text><view class="group"><ListRow icon="gear" tint="gray" title="设置" @tap="go('/pages/settings/index')" /><ListRow icon="info" tint="gray" title="关于 FaFa" @tap="toast('关于 FaFa')" /></view><view class="privacy"><uni-icons type="locked" size="14" color="#8E8E93" /><text>宠物数据默认仅自己可见</text></view><view class="spacer" /></view><AppTabbar active="mine" /></view></template>
<style scoped lang="scss">
@use '@/styles/tokens.scss' as *;
.screen { min-height: 100vh; background: $canvas; }.body { padding: 0 32rpx; }.user { display: flex; align-items: center; padding: 24rpx; border-radius: 29rpx; background: $surface; }.avatar { display: flex; width: 90rpx; height: 90rpx; align-items: center; justify-content: center; border-radius: 50%; background: $blue; color: #fff; font-size: 34rpx; font-weight: 600; }.user > view:nth-child(2) { display: flex; flex: 1; flex-direction: column; gap: 8rpx; margin-left: 18rpx; }.user > view:nth-child(2) text:first-child { color: $ink; font-size: 31rpx; font-weight: 600; }.user > view:nth-child(2) text:last-child { color: $tertiary; font-size: 21rpx; }.section-label { display: block; margin: 42rpx 0 14rpx 24rpx; color: $secondary; font-size: 24rpx; font-weight: 500; }.pet { display: flex; align-items: center; padding: 18rpx 22rpx; border-radius: 28rpx; background: $surface; }.pet image { width: 66rpx; height: 66rpx; border-radius: 50%; }.pet > view { display: flex; flex: 1; flex-direction: column; gap: 6rpx; margin-left: 15rpx; }.pet text:first-child { color: $ink; font-size: 27rpx; font-weight: 600; }.pet text:last-child { color: $tertiary; font-size: 20rpx; }.group { @include grouped-surface; }.privacy { display: flex; align-items: center; justify-content: center; gap: 7rpx; margin-top: 32rpx; color: $tertiary; font-size: 20rpx; }.spacer { height: 155rpx; }
</style>
